const selfHelpKeywords = [
    "help",
    "assistance",
    "support",
    "advice",
    "guidance",
    "counseling",
    "therapy",
    "motivation",
    "motivate",
    "motivational",
    "inspiration",
    "empowerment",
    "self-improvement",
    "self-care",
    "well-being",
    "mental health",
    "emotional support",
    "problem-solving",
    "personal growth",
    "positivity",
    "confidence",
    "self-esteem",
    "stress management",
    "anxiety relief",
    "depression help",
    "life coaching",
    "mindfulness",
    "positive thinking",
    "goal setting",
    "self-reflection",
    "self-discovery",
    "inner peace",
    "emotional wellness",
    "self-compassion",
    "resilience",
    "self-empowerment",
    "confidence building",
    "inner strength",
    "self-awareness",
    "mindset",
    "mental wellness",
    "mental clarity",
    "overcoming challenges",
    "self-motivation",
    "self-help books",
    "self-help resources",
    "growth mindset",
    "emotional intelligence",
    "life balance",
    "wellness practices",
    "lifestyle",
    "self-help tips",
    "relationship",
    "relationships",
    // Add more keywords as needed
];

export default selfHelpKeywords;